services:
  api:
    image: stackcalc-api-image
    container_name: stackcalc-api
    build:
      context: ..
      dockerfile: docker/StackCalc.Api.Dockerfile
    environment:
      - STACKCALC_API_HOST=${STACKCALC_API_HOST}
      - STACKCALC_API_PORT=${STACKCALC_API_PORT}
      - STACKCALC_API_BROKER_URL=${STACKCALC_API_BROKER_URL}
      - STACKCALC_API_WORKER_TASKNAME=${STACKCALC_API_WORKER_TASKNAME}
      - STACKCALC_API_BACKEND_URL=${STACKCALC_API_BACKEND_URL}
    ports:
      - 8000:8000
    depends_on:
      - rabbitmq
      - redis
  worker:
    image: stackcalc-worker-image
    container_name: stackcalc-worker
    build:
      context: ..
      dockerfile: docker/StackCalc.Worker.Dockerfile
    environment:
      - STACKCALC_API_BROKER_URL=${STACKCALC_API_BROKER_URL}
      - STACKCALC_API_BACKEND_URL=${STACKCALC_API_BACKEND_URL}
      - CELERY_WORKER_NAME=${CELERY_WORKER_NAME}
    depends_on:
      - rabbitmq
      - redis
